added fsl install dn check

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,6 +1,5 @@
 language: r
 warnings_are_errors: true
-sudo: false
 cache: packages
 use_bioc: true
 bioc_required: true
@@ -16,6 +15,19 @@ env:
 r_check_args: "--as-cran --install-args=--build"
 
 before_install:
+  - if [ "$TRAVIS_OS_NAME" = "linux" ]; 
+      then 
+        sudo apt-get update -qq ;
+        sudo apt-get install libmng2 ; 
+        sudo apt-get install libmng1 ; 
+        sudo updatedb;
+    fi
+  - wget https://fsl.fmrib.ox.ac.uk/fsldownloads/fslinstaller.py || echo "couldn't download";  
+  - python --version
+  - if [[ -f fslinstaller.py]]; 
+    then
+      travis_wait 100 sudo python fslinstaller.py -d /usr/local/fsl --quiet || echo "couldn't install";    
+    fi
   - export PROJ_DIR=`basename $PWD`    
   - fname=travis_helpers.sh
   - wget -O ${fname} http://bit.ly/travis_helpers
